#!/bin/bash
set -e 

sudo docker stop $(sudo docker ps -q --filter ancestor=morozovme/rvproxy )
sudo docker rm $(sudo docker ps --all -q --filter ancestor=morozovme/rvproxy )
sudo docker build -t morozovme/rvproxy . 
sudo docker run -d -p 80:80 morozovme/rvproxy
