#!/bin/bash
set -e 

sudo docker-compose down --rmi all
sudo docker-compose up -d
#sudo docker stop $(sudo docker ps -q --filter ancestor=mikefrostov/rvproxy )
#sudo docker rm $(sudo docker ps --all -q --filter ancestor=mikefrostov/rvproxy )
#sudo docker build -t mikefrostov/rvproxy . 
#sudo docker run -d -p 80:80 mikefrostov/rvproxy
